name: Deploy to Digital Ocean
on: 
    push:
        branches: [main]

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Deploy file
          uses: wlixcc/SFTP-Deploy-Action@v1.2.4
          with:
            username: ${{ secrets.SSH_USERNAME}}
            password: ${{ secrets.SSH_PASSWORD }}
            server: ${{ secrets.SSH_HOST }}
            #ssh_private_key: ${{ secrets.SSH_KEY }}
            port: 22
            local_path: './*'
            remote_path: '/var/www/html'
            sftp_only: true

            script: |
              cd /var/www/html 
              mkdir apps
              echo 'Deployment successful to digital ocean'
