on:
  push:
    branches:
      - main
name: 🚀 Deploy test website on push
jobs:
  web-deploy:
    name: 🎉 Deploy DU Website
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2.3.2

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: 198.211.115.230
          username: ${{ secrets.ftp_username}}
          password: ${{ secrets.ftp_password }}
          server-dir: /var/www/html/
          
