on:
  push:
    branches:
      - main
name: 🚀 Deploy DU website on push
jobs:
  web-deploy:
    name: 🎉 Deploy DU Website
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2.3.2

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@master
        with:
          server: ${{ secrets.DU_HOST}}
          username: ${{ secrets.DU_USERNAME}}
          password: ${{ secrets.DU_PASSWORD }}
          timeout: 30000000
          protocol: ftps
          server-dir: /gitactions/
