on:
    push:
      branches:
        - main
name: 🚀 Deploy DU website on push
jobs:
    web-deploy:
      name: 🎉 Deploy DU Website
      runs-on: ubuntu-latest
      steps:
        - name: 🚚 Get latest code
          uses: actions/checkout@v2.3.2
  
        - name: 📂 Sync files
          uses: SamKirkland/FTP-Deploy-Action@master
          with:
            server: ${{ secrets.SSH_HOST}}
            username: ${{ secrets.SSH_USERNAME}}
            password: ${{ secrets.SSH_PASSWORD}}
            timeout: 30000000
            server-dir: /var/www/html/
            protocol: sftp
            port: 22